# Generated by Django 4.0.6 on 2022-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nro_pedido',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
