# Generated by Django 4.0.6 on 2022-07-19 03:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pedido_monto_total_alter_pedido_nro_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
