# Generated by Django 3.2 on 2022-12-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('tamaño', 'TAMAÑO'), ('modelo', 'MODELO'), ('color', 'COLOR')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='panel.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='panel.producto')),
            ],
        ),
    ]
