-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 22:06:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_smartdevs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_smartdevs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_smartdevs` DEFAULT CHARACTER SET utf8 ;
USE `db_smartdevs` ;

-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_ubicacion` (
  `ubicacion_id` INT NOT NULL AUTO_INCREMENT,
  `ubicacion_pais` VARCHAR(255) NOT NULL,
  `ubicacion_ciudad` VARCHAR(255) NOT NULL,
  `ubicacion_codigo` VARCHAR(50) NULL,
  PRIMARY KEY (`ubicacion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_modalidad` (
  `modalidad_id` INT NOT NULL AUTO_INCREMENT,
  `modalidad_descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`modalidad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_area` (
  `area_id` INT NOT NULL AUTO_INCREMENT,
  `area_descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`area_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_periodo` (
  `periodo_id` INT NOT NULL AUTO_INCREMENT,
  `periodo_descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`periodo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_nivel` (
  `nivel_id` INT NOT NULL AUTO_INCREMENT,
  `nivel_descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nivel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_oferta` (
  `oferta_id` INT NOT NULL AUTO_INCREMENT,
  `oferta_titulo` VARCHAR(255) NOT NULL,
  `oferta_fec_pub` DATE NOT NULL COMMENT 'fecha publicacion',
  `oferta_fec_fin` DATE NOT NULL,
  `oferta_resumen` TEXT NULL,
  `oferta_detalle` TEXT NULL,
  `oferta_estado` INT NOT NULL DEFAULT 1,
  `oferta_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `ubicacion_id` INT NOT NULL,
  `modalidad_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `periodo_id` INT NOT NULL,
  `nivel_id` INT NOT NULL,
  PRIMARY KEY (`oferta_id`),
  INDEX `fk_tbl_oferta_tbl_ubicacion_idx` (`ubicacion_id` ASC) VISIBLE,
  INDEX `fk_tbl_oferta_tbl_modalidad1_idx` (`modalidad_id` ASC) VISIBLE,
  INDEX `fk_tbl_oferta_tbl_area1_idx` (`area_id` ASC) VISIBLE,
  INDEX `fk_tbl_oferta_tbl_periodo1_idx` (`periodo_id` ASC) VISIBLE,
  INDEX `fk_tbl_oferta_tbl_nivel1_idx` (`nivel_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_oferta_tbl_ubicacion`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `db_smartdevs`.`tbl_ubicacion` (`ubicacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_oferta_tbl_modalidad1`
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `db_smartdevs`.`tbl_modalidad` (`modalidad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_oferta_tbl_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `db_smartdevs`.`tbl_area` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_oferta_tbl_periodo1`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `db_smartdevs`.`tbl_periodo` (`periodo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_oferta_tbl_nivel1`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `db_smartdevs`.`tbl_nivel` (`nivel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_postulante` (
  `postulante_id` INT NOT NULL AUTO_INCREMENT,
  `postulante_nombres` VARCHAR(255) NOT NULL,
  `postulante_apellidos` VARCHAR(255) NOT NULL,
  `postulante_nrodocide` VARCHAR(100) NOT NULL,
  `postulante_fecnac` DATE NOT NULL,
  `postulante_genero` CHAR(1) NOT NULL,
  `postulante_estado` CHAR(1) NOT NULL DEFAULT '1',
  `postulante_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `postulante_perfil` TEXT NULL,
  PRIMARY KEY (`postulante_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_tipo_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_tipo_contacto` (
  `tipo_contacto_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_contacto_descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tipo_contacto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_postulante_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_postulante_contacto` (
  `postulante_contacto_id` INT NOT NULL AUTO_INCREMENT,
  `postulante_contacto_valor` VARCHAR(255) NOT NULL,
  `postulante_contacto_estado` CHAR(1) NOT NULL DEFAULT '1',
  `postulante_contacto_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `tipo_contacto_id` INT NOT NULL,
  `postulante_id` INT NOT NULL,
  PRIMARY KEY (`postulante_contacto_id`),
  INDEX `fk_tbl_postulante_contacto_tbl_tipo_contacto1_idx` (`tipo_contacto_id` ASC) VISIBLE,
  INDEX `fk_tbl_postulante_contacto_tbl_postulante1_idx` (`postulante_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_postulante_contacto_tbl_tipo_contacto1`
    FOREIGN KEY (`tipo_contacto_id`)
    REFERENCES `db_smartdevs`.`tbl_tipo_contacto` (`tipo_contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_postulante_contacto_tbl_postulante1`
    FOREIGN KEY (`postulante_id`)
    REFERENCES `db_smartdevs`.`tbl_postulante` (`postulante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_tipo_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_tipo_estudio` (
  `tipo_estudio_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_estudio_descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tipo_estudio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_postulante_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_postulante_estudio` (
  `postulante_estudio_id` INT NOT NULL AUTO_INCREMENT,
  `postulante_estudio_titulo` VARCHAR(255) NOT NULL,
  `postulante_estudio_institucion` VARCHAR(255) NOT NULL,
  `postulante_estudio_fecini` DATE NOT NULL,
  `postulante_estudio_fecfin` DATE NULL,
  `postulante_estudio_estado` CHAR(1) NOT NULL DEFAULT '1',
  `postulante_estudio_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `tipo_estudio_id` INT NOT NULL,
  `postulante_id` INT NOT NULL,
  PRIMARY KEY (`postulante_estudio_id`),
  INDEX `fk_postulante_estudio_tipo_estudio1_idx` (`tipo_estudio_id` ASC) VISIBLE,
  INDEX `fk_postulante_estudio_tbl_postulante1_idx` (`postulante_id` ASC) VISIBLE,
  CONSTRAINT `fk_postulante_estudio_tipo_estudio1`
    FOREIGN KEY (`tipo_estudio_id`)
    REFERENCES `db_smartdevs`.`tbl_tipo_estudio` (`tipo_estudio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_estudio_tbl_postulante1`
    FOREIGN KEY (`postulante_id`)
    REFERENCES `db_smartdevs`.`tbl_postulante` (`postulante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_postulante_experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_postulante_experiencia` (
  `postulante_experiencia_id` INT NOT NULL AUTO_INCREMENT,
  `postulante_experiencia_puesto` VARCHAR(255) NOT NULL,
  `postulante_experiencia_empresa` VARCHAR(255) NOT NULL,
  `postulante_experiencia_detalle` TEXT NOT NULL,
  `postulante_experiencia_fecini` DATE NOT NULL,
  `postulante_experiencia_fecfin` DATE NULL,
  `postulante_experiencia_estado` CHAR(1) NOT NULL DEFAULT '1',
  `postulante_experiencia_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `postulante_id` INT NOT NULL,
  PRIMARY KEY (`postulante_experiencia_id`),
  INDEX `fk_tbl_postulante_experiencia_tbl_postulante1_idx` (`postulante_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_postulante_experiencia_tbl_postulante1`
    FOREIGN KEY (`postulante_id`)
    REFERENCES `db_smartdevs`.`tbl_postulante` (`postulante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_oferta_postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_oferta_postulante` (
  `oferta_postulante_id` INT NOT NULL AUTO_INCREMENT,
  `oferta_postulante_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `oferta_postulante_estado` CHAR(1) NOT NULL DEFAULT '1',
  `oferta_id` INT NOT NULL,
  `postulante_id` INT NOT NULL,
  PRIMARY KEY (`oferta_postulante_id`),
  INDEX `fk_tbl_oferta_postulante_tbl_oferta1_idx` (`oferta_id` ASC) VISIBLE,
  INDEX `fk_tbl_oferta_postulante_tbl_postulante1_idx` (`postulante_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_oferta_postulante_tbl_oferta1`
    FOREIGN KEY (`oferta_id`)
    REFERENCES `db_smartdevs`.`tbl_oferta` (`oferta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_oferta_postulante_tbl_postulante1`
    FOREIGN KEY (`postulante_id`)
    REFERENCES `db_smartdevs`.`tbl_postulante` (`postulante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_smartdevs`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartdevs`.`tbl_usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nombre` VARCHAR(255) NOT NULL,
  `usuario_password` VARCHAR(255) NOT NULL,
  `usuario_fecreg` TIMESTAMP NOT NULL DEFAULT NOW(),
  `usuario_estado` CHAR(1) NOT NULL DEFAULT '1',
  `postulante_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_tbl_usuario_tbl_postulante1_idx` (`postulante_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_usuario_tbl_postulante1`
    FOREIGN KEY (`postulante_id`)
    REFERENCES `db_smartdevs`.`tbl_postulante` (`postulante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
