version : '3'

services:
  web:
    build: .
    image: express-web:1.0
    ports:
      - "5006:5005"
  
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: codigo
    volumes:
      - data:/var/lib/mysql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"

volumes:
  data:
    driver: local

